export const ADD_EDUCATION = 'ADD_EDUCATION';
export const ADD_IS_EDUCATION_LIST_VISIBLE = 'ADD_IS_EDUCATION_LIST_VISIBLE';
export const SET_EDUCATION_LIST = 'SET_EDUCATION_LIST';
export const ADD_SELECTED_EDUCATION = 'ADD_SELECTED_EDUCATION';

export const ADD_EXPERIENCE = 'ADD_EXPERIENCE';
export const ADD_IS_EXPERIENCE_LIST_VISIBLE = 'ADD_IS_EXPERIENCE_LIST_VISIBLE';
export const SET_EXPERIENCE_LIST = 'SET_EXPERIENCE_LIST';
export const ADD_SELECTED_EXPERIENCE = 'ADD_SELECTED_EXPERIENCE';

export const ADD_BASIC_INFORMATION = 'ADD_BASIC_INFORMATION';

export const ADD_CERTIFICATE = 'ADD_CERTIFICATE';
export const ADD_IS_CERTIFICATE_LIST_VISIBLE = 'ADD_IS_CERTIFICATE_LIST_VISIBLE';
export const SET_CERTIFICATE_LIST = 'SET_CERTIFICATE_LIST';
export const ADD_SELECTED_CERTIFICATE = 'ADD_SELECTED_CERTIFICATE';

export const ADD_LANGUAGE = 'ADD_LANGUAGE';
export const ADD_IS_LANGUAGE_LIST_VISIBLE = 'ADD_IS_LANGUAGE_LIST_VISIBLE';
export const SET_LANGUAGE_LIST = 'SET_LANGUAGE_LIST';
export const ADD_SELECTED_LANGUAGE = 'ADD_SELECTED_LANGUAGE';

export const ADD_SKILL = 'ADD_SKILL';
export const SET_SKILLS_LIST = 'SET_SKILLS_LIST';

export const ADD_HOBBY = 'ADD_HOBBY';
export const SET_HOBBIES_LIST = 'SET_HOBBIES_LIST';

export const ADD_USER = 'ADD_USER';
export const ADD_TOKEN = 'ADD_TOKEN';

export const ADD_ALERT_MESSAGE = 'ADD_ALERT_MESSAGE'