export const ADD_EDUCATION = "ADD_EDUCATION";
export const SET_EDUCATION_LIST = "SET_EDUCATION_LIST";
export const ADD_SELECTED_EDUCATION = "ADD_SELECTED_EDUCATION";

export const ADD_EXPERIENCE = "ADD_EXPERIENCE";
export const SET_EXPERIENCE_LIST = "SET_EXPERIENCE_LIST";
export const ADD_SELECTED_EXPERIENCE = "ADD_SELECTED_EXPERIENCE";

export const ADD_BASIC_INFORMATION = "ADD_BASIC_INFORMATION";

export const ADD_CERTIFICATE = "ADD_CERTIFICATE";
export const SET_CERTIFICATE_LIST = "SET_CERTIFICATE_LIST";
export const ADD_SELECTED_CERTIFICATE = "ADD_SELECTED_CERTIFICATE";

export const ADD_LANGUAGE = "ADD_LANGUAGE";
export const SET_LANGUAGE_LIST = "SET_LANGUAGE_LIST";
export const ADD_SELECTED_LANGUAGE = "ADD_SELECTED_LANGUAGE";

export const SET_RESUME_SKILLS = "SET_RESUME_SKILLS";

export const SET_RESUME_SOFT_SKILLS = "SET_RESUME_SOFT_SKILLS";

export const ADD_USER = "ADD_USER";
export const ADD_TOKEN = "ADD_TOKEN";
export const SET_IS_USER_LOADED = "SET_IS_USER_LOADED";

export const ADD_ALERT_MESSAGE = "ADD_ALERT_MESSAGE";

export const ADD_LANGUAGES_LIST = "ADD_LANGUAGES_LIST";
export const ADD_LANGUAGE_LEVELS_LIST = "ADD_LANGUAGE_LEVELS_LIST";
